# Generated by Django 2.1.5 on 2019-01-22 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190122_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commits',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='posts.Post', verbose_name='文章'),
        ),
    ]
